pipeline {
    agent { label 'maven-label' }
    tools {
       
        maven "maven-3.6.2"
    }
    stages {
        stage('prep') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/qf-collect/collectcore.git'
            }
        }
        stage('build') {
            steps {
              sh 'mvn -f pom.xml -s settings.xml clean deploy'
            }
            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                  //  slackSend channel: 'testchannel', message: 'build completed successfully'
                }
                
            }
        }
        stage('deploy') {
            steps {
                echo 'going to strat deploy soon'
            }
        }
        stage('testing') {
            steps {
                echo 'can be deon once deploy task completed'
            }
        }
    }
}
